version: '3.8'

services:
  db:
    container_name: db
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lfgho
    ports:
      - "6432:5432"
    volumes:
      -  pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
